config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'
  get '/search' => 'search#search'
  get 'contacts' => 'contacts#index'
  get 'contacts/confirm' => redirect("/contacts")
  get 'contacts/thanks' => redirect("/contacts")
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'
  resources :rooms
  resources :notifications, only: :index do
    delete :destroy_all, on: :collection
  end
  
  # Public側ルーティング
  devise_for :end_users, controllers: {
    registrations: 'public/devise/registrations',
    sessions:'public/devise/sessions',
    omniauth_callbacks: 'public/devise/omniauth_callbacks'
  }
  devise_scope :end_user do
    post 'guest_sign_in' => 'public/devise/sessions#new_guest'
  end

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/terms' => 'homes#terms', as: 'terms'
    get 'homes/policy' => 'homes#policy', as: 'policy'
    
    resources :end_users, only:[:edit,:show,:update] do
      member do
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :cocktails do
      resource :favorites, only: [:create, :destroy]
      resources :rates, only: [:create, :destroy]
      post :search, on: :collection
      post :multiple_search, on: :collection
      get :ranking, on: :collection
    end
    
    resources :ingredients, only:[:index] do
      post :search, on: :collection
    end

  end

  # Admin側ルーティング
  devise_scope :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/devise/sessions',
    }
  end

  namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :end_users, only: [:index, :show] do
      member do
        patch :withdraw
        patch :unfreeze
      end
    end
    resources :cocktails do
      collection do
        get :get_api_cocktails
        post :search
        get :similar_cocktail
      end
    end
    resources :ingredients, only: [:index, :create, :update, :destroy] do
      post :search, on: :collection
    end
  end
    
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2 twitter]
  attachment :image

  has_many :cocktails
  has_many :favorites
  has_many :favorite_cocktails, through: :favorites, source: :cocktail
  has_many :rates, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  has_many :sns_credentials, dependent: :destroy
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def followed_by?(end_user)
    passive_relationships.find_by(following_id: end_user.id).present?
  end

  def active_for_authentication?
    self.is_active == true
  end

  def inactive_message
    "このアカウントは退会されています"
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name = 'Guest'
      end_user.birth_date = '1990-01-01'
    end
  end

  def self.without_sns_data(auth)
    end_user = EndUser.where(email: auth.info.email).first

      if end_user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          end_user_id: end_user.id
        )
      else
        end_user = EndUser.create(
          name: auth.info.name,
          email: auth.info.email,
          birth_date: '1991-11-05',
          password: Devise.friendly_token[0, 20]
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { end_user: end_user ,sns: sns}
    end

   def self.with_sns_data(auth, snscredential)
    end_user = EndUser.where(id: snscredential.end_user_id).first
    unless end_user.present?
      end_user = EndUser.create(
        name: auth.info.name,
        email: auth.info.email,
        birth_date: '1991-11-05',
        password: Devise.friendly_token[0, 20]
      )
    end
    return {end_user: end_user}
   end

   def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      end_user = with_sns_data(auth, snscredential)[:end_user]
      sns = snscredential
    else
      end_user = without_sns_data(auth)[:end_user]
      sns = without_sns_data(auth)[:sns]
    end
    return { end_user: end_user ,sns: sns}
  end

  def create_notification_follow!(current_end_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_end_user.id, id, 'follow'])
    if temp.blank?
      notification = current_end_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.all
  end

  def show
    @user = EndUser.find(params[:id])
    @recipes = Cocktail.where(end_user_id: @user.id)
    @favorite_cocktails = @user.favorite_cocktails
    @follow_users = @user.followings
  end

  def withdraw
    @end_user = EndUser.find(params[:id])
    @end_user.update(is_active: false)
    flash[:notice] = "アカウントを凍結しました。"
    redirect_to admins_end_users_path
  end

  def unfreeze
    @end_user = EndUser.find(params[:id])
    @end_user.update(is_active: true)
    flash[:notice] = "アカウントを復帰しました。"
    redirect_to admins_end_users_path
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/views/admins/end_users/edit.html.slim
h1
  | Admins::EndUsers#edit
p
  | Find me in app/views/admins/end_users/edit.html.erb

app/views/admins/end_users/index.html.slim
.container
  .row.justify-content-center
    .col-10.table-responsive
      h4
        | ユーザー一覧

      table.table.text-nowrap
        thead
          tr
            th 
            th ユーザー名
            th メールアドレス
            th 誕生日
            th 投稿レシピ数
            th ステータス
        tbody
          - @end_users.each do |end_user|
            tr
              th = attachment_image_tag end_user, :image, format: 'jpeg', class: "img-raised rounded-circle img-responsive", fallback: "no_image.png", size: "50x50"
              th = link_to end_user.name, admins_end_user_path(end_user.id)
              th = end_user.email
              th = end_user.birth_date
              th = end_user.cocktails.size
              th
                - if end_user.is_active
                  | 有効
                  = link_to "BAN", withdraw_admins_end_user_path(end_user.id), method: :patch, class:"btn btn-danger", data:{confirm:'本当に凍結しますか？'}
                - else
                  | 退会済み
                  = link_to "復帰", unfreeze_admins_end_user_path(end_user.id), method: :patch, class:"btn btn-success", data:{confirm:'本当に復帰しますか？'}

app/views/admins/end_users/show.html.slim
.container
  .profile-page
    .main-raised
      .row.justify-content-center.flex
        .col-lg-6.offset-md-3
          .profile
            .avatar
              = attachment_image_tag @user, :image, format: 'jpeg', class: "img-raised rounded-circle img-responsive", fallback: "no_image.png", size: "160x160"

            .name
              h2.title = @user.name
              = link_to withdraw_admins_end_user_path(@user.id), method: :patch, class:"btn btn-fab btn-danger btn-round", data:{confirm:'本当にBANしますか？'}
                i.fas.fa-trash-alt

      .description.text-center
        p = @user.introduction 

      .row
        .col
          .profile-tabs
            .mytabs style="width: 90%;"
              .tab-buttons.text-nowrap
                span.content1 マイレシピ
                span.content2 お気に入り
                span.content3 フォローユーザー
                #lamp.content1

              .tab-content
                #myrecipe.content1
                  - if @recipes.presence
                    .table-responsive
                      table.table
                        thead.text-nowrap
                          tr
                            th
                            th 名前
                            th ベース
                            th テイスト
                            th スタイル
                            th アルコール(%)
                            th キャッチコピー
                        tbody
                        - @recipes.each do |recipe|
                          tr
                            th = attachment_image_tag recipe, :image, fallback:"default.jpeg", class:"cocktail-img img-raised", width:"80", height:"80"
                            th.text-nowrap
                              = link_to admins_cocktail_path(recipe.id), class:"grid__link"
                                = recipe.name
                            th = recipe.base_name
                            th = recipe.taste_name
                            th = recipe.style_name
                            th = recipe.alcohol
                            th = recipe.cocktail_desc
                  - else
                    .text-center
                      h4 マイレシピが登録されていません

                #favorite.content2
                  - if @favorite_cocktails.presence
                    .masonry
                      - @favorite_cocktails.each do |cocktail|
                          .grid
                            = attachment_image_tag cocktail, :image, fallback:"default.jpeg", class:"img-raised rounded"
                            .grid__body
                              .relative
                                = link_to admins_cocktail_path(cocktail.id), class:"grid__link"
                                  h1.grid__title = cocktail.name
                              .mt-auto
                                span.grid__tag ##{cocktail.base_name}
                  - else
                    h4 お気に入りが登録されていません。

                #follow.content3
                  - if @follow_users.presence
                    table.table
                      thead
                        tr
                          th 
                          th ユーザー名
                          th 投稿レシピ数
                          th
                      tbody
                        - @follow_users.each do |user|
                          tr
                            th = attachment_image_tag user, :image, format: 'jpeg', class: "img-raised rounded-circle img-responsive", fallback: "no_image.png", size: "50x50"
                            th = link_to "#{user.name}", admins_end_user_path(user.id)
                            th = user.cocktails.size

                  - else
                    h4 フォローしているユーザーがいません。