config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'
  get '/search' => 'search#search'
  get 'contacts' => 'contacts#index'
  get 'contacts/confirm' => redirect("/contacts")
  get 'contacts/thanks' => redirect("/contacts")
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'
  resources :rooms
  resources :notifications, only: :index do
    delete :destroy_all, on: :collection
  end
  
  # Public側ルーティング
  devise_for :end_users, controllers: {
    registrations: 'public/devise/registrations',
    sessions:'public/devise/sessions',
    omniauth_callbacks: 'public/devise/omniauth_callbacks'
  }
  devise_scope :end_user do
    post 'guest_sign_in' => 'public/devise/sessions#new_guest'
  end

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/terms' => 'homes#terms', as: 'terms'
    get 'homes/policy' => 'homes#policy', as: 'policy'
    
    resources :end_users, only:[:edit,:show,:update] do
      member do
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :cocktails do
      resource :favorites, only: [:create, :destroy]
      resources :rates, only: [:create, :destroy]
      post :search, on: :collection
      post :multiple_search, on: :collection
      get :ranking, on: :collection
    end
    
    resources :ingredients, only:[:index] do
      post :search, on: :collection
    end

  end

  # Admin側ルーティング
  devise_scope :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/devise/sessions',
    }
  end

  namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :end_users, only: [:index, :show] do
      member do
        patch :withdraw
        patch :unfreeze
      end
    end
    resources :cocktails do
      collection do
        get :get_api_cocktails
        post :search
        get :similar_cocktail
      end
    end
    resources :ingredients, only: [:index, :create, :update, :destroy] do
      post :search, on: :collection
    end
  end
    
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :type_name, presence: true
  validates :alcohol, presence: true

  enum type_name: {
    アルコール: 1,
    ノンアルコール: 2,
    副材料: 3,
  }

  has_many :ingredient_relations, dependent: :destroy
  has_many :cocktails, through: :ingredient_relations
end

app/controllers/admins/ingredients_controller.rb
class Admins::IngredientsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @ingredients = Ingredient.all
    @new_ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:notice] = '材料を追加しました'
      redirect_to admins_ingredients_path
    else
      flash[:alert] = '追加に失敗しました'
      @ingredients = Ingredient.all
      @new_ingredient = Ingredient.new
      render 'index'
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      flash[:notice] = '材料情報を更新しました'
    end
    redirect_to admins_ingredients_path
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    destroy_name = ingredient.name
    if ingredient.destroy
      flash[:notice] = "#{destroy_name}を削除しました"
    else
      flash[:notice] = '削除に失敗しました'
    end
    redirect_to admins_ingredients_path
  end

  def search
    @ingredients = Ingredient.where(type_name: params[:name])
    @new_ingredient = Ingredient.new
    render 'admins/ingredients/index'
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name,:type_name,:alcohol)
  end

end

app/helpers/admins/ingredients_helper.rb
module Admins::IngredientsHelper
end

app/views/admins/ingredients/index.html.slim
.container
  .row
    .col-10.table-responsive
      .navbar.ingredient-type-box
        ul.nav.flex.justify-content-center
          li 絞り込み：
          li = link_to "全て", admins_ingredients_path, class:"nav-item nav-link btn btn-light"
          - Ingredient.type_names.keys.each do |type_name|
            li = link_to "#{type_name}", search_admins_ingredients_path(:name => type_name), method: :post, class:"nav-item nav-link btn btn-light"
      
      table.table.text-nowrap
        thead
          tr
            th 材料名
            th タイプ
            th アルコール度数(%)
            th
            th
        tbody
          = form_with model:[:admins,@new_ingredient], class:"form-control",local: true do |f|
            = render 'shared/error_messages', model: f.object
            tr
              th = f.text_field :name, placeholder:"材料名を入力"
              th = f.select :type_name, options_for_select(Ingredient.type_names.keys)
              th = f.number_field :alcohol, min: '0', max: '99'
              th = f.submit "追加",class: "btn btn-success"
                th
      
      table.table
        thead
          tr
            th 材料名
            th タイプ
            th アルコール度数(%)
            th 
            th 
        tbody
          - @ingredients.each do |ingredient|
            tr
              th = link_to ingredient.name, search_admins_cocktails_path(:name => "#{ingredient.name}", :search_key => "ingredient"), method: :post
              = form_with model: [:admins,ingredient], method: :patch, local: true do |fi|
                th = fi.select :type_name, options_for_select(Ingredient.type_names.keys, ingredient.type_name), class: 'form-control'
                th = fi.number_field :alcohol, value: ingredient.alcohol
                th = fi.submit "変更", class:"btn btn-info"
              th = link_to "削除", admins_ingredient_path(ingredient.id), method: :delete,class:"btn btn-danger"