config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'
  get '/search' => 'search#search'
  get 'contacts' => 'contacts#index'
  get 'contacts/confirm' => redirect("/contacts")
  get 'contacts/thanks' => redirect("/contacts")
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'
  resources :rooms
  resources :notifications, only: :index do
    delete :destroy_all, on: :collection
  end
  
  # Public側ルーティング
  devise_for :end_users, controllers: {
    registrations: 'public/devise/registrations',
    sessions:'public/devise/sessions',
    omniauth_callbacks: 'public/devise/omniauth_callbacks'
  }
  devise_scope :end_user do
    post 'guest_sign_in' => 'public/devise/sessions#new_guest'
  end

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/terms' => 'homes#terms', as: 'terms'
    get 'homes/policy' => 'homes#policy', as: 'policy'
    
    resources :end_users, only:[:edit,:show,:update] do
      member do
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :cocktails do
      resource :favorites, only: [:create, :destroy]
      resources :rates, only: [:create, :destroy]
      post :search, on: :collection
      post :multiple_search, on: :collection
      get :ranking, on: :collection
    end
    
    resources :ingredients, only:[:index] do
      post :search, on: :collection
    end

  end

  # Admin側ルーティング
  devise_scope :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/devise/sessions',
    }
  end

  namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :end_users, only: [:index, :show] do
      member do
        patch :withdraw
        patch :unfreeze
      end
    end
    resources :cocktails do
      collection do
        get :get_api_cocktails
        post :search
        get :similar_cocktail
      end
    end
    resources :ingredients, only: [:index, :create, :update, :destroy] do
      post :search, on: :collection
    end
  end
    
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @cocktails = Cocktail.all
    @pv_cocktails = Cocktail.order(impressions_count: 'DESC').limit(10)
    @favorites_cocktails = Cocktail.select('cocktails.*', 'count(favorites.id) AS favs').left_joins(:favorites).group('cocktails.id').order('favs desc').limit(10)
    rates_array = Rate.group(:cocktail_id).average(:rate).sort_by{ |_, v| v }.reverse.to_h.keys
    @rates_cocktails = Cocktail.find(rates_array).sort_by{ |o| rates_array.index(o.id)}.take(10)
  end
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/views/admins/homes/top.html.slim
.container
  .row
    .col-lg-4
      table.table
        h5 メインベースレシピ数
        thead
          tr
            th ジャンル
            th レシピ数
        tr
          th ジン
          th = @cocktails.where(base_name: "ジン").size
        tr
          th ウォッカ
          th = @cocktails.where(base_name: "ウォッカ").size
        tr
          th  テキーラ
          th = @cocktails.where(base_name: "テキーラ").size
        tr
          th  ラム
          th = @cocktails.where(base_name: "ラム").size
        tr
          th  ウイスキー
          th = @cocktails.where(base_name: "ウイスキー").size
        tr
          th レシピ総数
          th = @cocktails.size

    .col-lg-7
      table.table
        h5 データの更新
        thead
          tr
            th 概要
            th
            th 前回更新日
        tbody
          tr
            th Cocktail-fのレシピを更新
            th = link_to "更新", get_api_cocktails_admins_cocktails_path, class:"btn btn-primary"
            - if Cocktail.where(end_user_id: 1).presence
              th = Cocktail.where(end_user_id: 1).order(:created_at).last.created_at.strftime('%Y/%m/%d/%H:%M')
          tr
            th レシピ類似度の更新
            th = link_to "更新", similar_cocktail_admins_cocktails_path, class:"btn btn-primary"
            - if Similar.all.present?
              th = Similar.order(:updated_at).last.updated_at.strftime('%Y/%m/%d/%H:%M')

  h5 ランキング
  .row
    .col
      .tab-buttons
        span.content1
          i.fas.fa-medal  PV
        span.content2
          i.far.fa-heart  お気に入り
        span.content3 
          i.far.fa-star  評価
        #lamp.content1

      .tab-content
        #myrecipe.content1
          table.table
            thead
              tr
                th
                  | 順位
                th
                  | レシピ名
                th
                  | 投稿者
                th
                  | PV数
            tbody
              - @pv_cocktails.each.with_index(1) do |cocktail, index|
                tr
                  td
                    = index
                    | 位
                  td
                    = link_to admins_cocktail_path(cocktail) do
                      = cocktail.name
                  td
                    = link_to admins_end_user_path(cocktail.end_user) do
                      = cocktail.end_user.name
                  td
                    = cocktail.impressions_count

        #favorite.content2
          table.table
            thead
              tr
                th
                  | 順位
                th
                  | レシピ名
                th
                  | 投稿者
                th
                  | お気に入り数
            tbody
              - @favorites_cocktails.each.with_index(1) do |cocktail, index|
                tr
                  td
                    = index
                    | 位
                  td
                    = link_to admins_cocktail_path(cocktail) do
                      = cocktail.name
                  td
                    = link_to admins_end_user_path(cocktail.end_user) do
                      = cocktail.end_user.name
                  td
                    = cocktail.favorites.count


        #follow.content3
          table.table
            thead
              tr
                th
                  | 順位
                th
                  | レシピ名
                th
                  | 投稿者
                th
                  | 評価
                th
                  | 評価数
            tbody
              - @rates_cocktails.each.with_index(1) do |cocktail, index|
                tr
                  td
                    = index
                    | 位
                  td
                    = link_to admins_cocktail_path(cocktail) do
                      = cocktail.name
                  td
                    = link_to admins_end_user_path(cocktail.end_user) do
                      = cocktail.end_user.name
                  td
                    p id="average-rate-#{cocktail.id}"
                    = render partial: "shared/star", locals: { cocktail: cocktail }
                  td
                    = cocktail.rates.count