config/routes.rb
Rails.application.routes.draw do
  root 'public/homes#top'
  get '/search' => 'search#search'
  get 'contacts' => 'contacts#index'
  get 'contacts/confirm' => redirect("/contacts")
  get 'contacts/thanks' => redirect("/contacts")
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'
  resources :rooms
  resources :notifications, only: :index do
    delete :destroy_all, on: :collection
  end
  
  # Public側ルーティング
  devise_for :end_users, controllers: {
    registrations: 'public/devise/registrations',
    sessions:'public/devise/sessions',
    omniauth_callbacks: 'public/devise/omniauth_callbacks'
  }
  devise_scope :end_user do
    post 'guest_sign_in' => 'public/devise/sessions#new_guest'
  end

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/terms' => 'homes#terms', as: 'terms'
    get 'homes/policy' => 'homes#policy', as: 'policy'
    
    resources :end_users, only:[:edit,:show,:update] do
      member do
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
    end
    
    resources :cocktails do
      resource :favorites, only: [:create, :destroy]
      resources :rates, only: [:create, :destroy]
      post :search, on: :collection
      post :multiple_search, on: :collection
      get :ranking, on: :collection
    end
    
    resources :ingredients, only:[:index] do
      post :search, on: :collection
    end

  end

  # Admin側ルーティング
  devise_scope :admins do
    devise_for :admins, controllers: {
      sessions: 'admins/devise/sessions',
    }
  end

  namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :end_users, only: [:index, :show] do
      member do
        patch :withdraw
        patch :unfreeze
      end
    end
    resources :cocktails do
      collection do
        get :get_api_cocktails
        post :search
        get :similar_cocktail
      end
    end
    resources :ingredients, only: [:index, :create, :update, :destroy] do
      post :search, on: :collection
    end
  end
    
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Jigger
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('favicon.ico')
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"
    link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css"
    link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Economica:700"
  body
    header
      .header-bar
        #logo
          = link_to root_path
            = image_tag "logo.png", size:"80x80"
        
        #search-form
          = form_with url: search_path, class:"form-inline",local: true , method: :get do |f|
            = f.text_field :content ,class:"form-search", placeholder:"カクテル名・材料名"
            = f.button :type => "submit"
              i.fas.fa-search

        #user-action.dropdown
          button.dropdown__btn id="dropdown__btn"
            - if end_user_signed_in?
              = attachment_image_tag current_end_user, :image, format: 'jpeg', class: "rounded-circle", fallback: "no_image.png", width:"40", height:"40"
              p.pc-screen = current_end_user.name
              i.fas.fa-angle-down.fa-lg.mgl-5
              - if unchecked_notifications.any?
                i.fas.fa-circle.notification-budge-icon style="color: red;"
            - elsif admin_signed_in?
              .btn Admin
              i.fas.fa-angle-down.fa-lg
            - else
              i.fas.fa-sign-in-alt.fa-lg
              p.pc-screen.mgl-5 ログインはこちら
          .dropdown__body
            ul.dropdown__list
              - if end_user_signed_in?
                li.dropdown__item = link_to 'マイページ', public_end_user_path(current_end_user), class:"dropdown__item-link"
                li.dropdown__item = link_to 'マイレシピ',  new_public_cocktail_path, class:"dropdown__item-link"
                li.dropdown__item = link_to 'ログアウト', destroy_end_user_session_path, method: :delete, class:"dropdown__item-link"
                li.dropdown__item = link_to '通知一覧', notifications_path, class:"dropdown__item-link"
                - if unchecked_notifications.any?
                  i.fas.fa-circle.notification-budge-dropdown style="color: red;"
              - elsif admin_signed_in?
                li.dropdown__item = link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"dropdown__item-link"
              - else
                li.dropdown__item = link_to '管理者ログイン',  new_admin_session_path, class:"dropdown__item-link"
                li.dropdown__item = link_to 'ゲストログイン',  guest_sign_in_path, method: :post, class:"dropdown__item-link"
                li.dropdown__item = link_to 'ログイン', new_end_user_session_path, class:"dropdown__item-link"
                li.dropdown__item = link_to '新規登録', new_end_user_registration_path, class:"dropdown__item-link"

        #nav-toggle.mobile-screen
          div
            span
            span
            span

        #gloval-nav
          nav
            ul  
              - if admin_signed_in?
                li = link_to 'TOP', admins_top_path
                li = link_to "カクテル一覧",admins_cocktails_path
                li = link_to "材料一覧",admins_ingredients_path
                li = link_to "ユーザー一覧",admins_end_users_path
              - else
                li = link_to "Cocktails",public_cocktails_path
                li = link_to "Ingredients", public_ingredients_path
                li = link_to "Terms", public_terms_path
                li = link_to "Ranking",ranking_public_cocktails_path
                li = link_to "Contact",contacts_path
                li = link_to "Policy",public_policy_path


        #left-link.pc-screen
          ul.flex
            - if admin_signed_in?
              li = link_to 'TOP', admins_top_path, class:"btn-border"
              li = link_to "Cocktails",admins_cocktails_path, class:"btn-border"
              li = link_to "Ingredients",admins_ingredients_path, class:"btn-border"
              li = link_to "Users",admins_end_users_path, class:"btn-border"
            - else
              li = link_to "Cocktails",public_cocktails_path, class:"btn-border", id:"linkbtn-cocktail"
              li = link_to "Ingredients", public_ingredients_path, class:"btn-border", id:"linkbtn-ingredient"
              li = link_to "Ranking",ranking_public_cocktails_path, class:"btn-border", id:"linkbtn-ranking"

        #right-link.pc-screen
          ul.flex
            - if admin_signed_in?
              p.header-text 管理者でログイン中
            - else
              li = link_to "Terms", public_terms_path, class:"btn-border", id:"linkbtn-term"
              li = link_to "Policy",public_policy_path, class:"btn-border", id:"linkbtn-policy"
              li = link_to "Contact",contacts_path, class:"btn-border", id:"linkbtn-contact"
        
        .search-box-toggle
          a.btn.js-modal-open href="#"
            i.fas.fa-search.fa-2x

    = render 'shared/search_modal'

    main
      .wrapper
        = yield

        #direct_messages_btn
          = link_to rooms_path, class:"btn"
            i.fas.fa-comments.fa-2x
            - if end_user_signed_in? && DirectMessage.new_message_count(current_end_user) != 0
              .new-message-badge
                = DirectMessage.new_message_count(current_end_user)
        
        #flash_messages
          = render 'shared/flash_messages'

      / footer
      /   p.text-center ©2020 Jigger.work

    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-ja.min.js" charset="utf-8"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js" charset="utf-8"
    script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"